chore: build.yml edit

diff --git a/.github/workflows/flutter_build.yml b/.github/workflows/flutter_build.yml
--- a/.github/workflows/flutter_build.yml
+++ b/.github/workflows/flutter_build.yml
@@ -56,9 +56,17 @@ jobs:
         run: flutter pub get
 
       - name: Build iOS (Release)
-        run: flutter build ios --release --no-codesign
+        run: flutter build ipa --release --no-codesign
+
+      - name: Check if IPA exists
+        run: |
+          if [ ! -f build/ios/archive/Runner.ipa ]; then
+            echo "IPA not found!"
+            exit 1
+          fi
+
       - name: Upload IPA to Artifacts
         uses: actions/upload-artifact@v2
         with:
           name: ios-release-ipa
-          path: build/ios/ipa/*.ipa
+          path: build/ios/archive/Runner.ipa
